### ISSUE TITLE
NSPanel laggy and not responsive 

### ISSUE THREAD

**Issue by geni0602** [Blackymas/NSPanel_HA_Blueprint#1405]
I have the Panel at least for 6-7 months. Till now there were not issues at all. From today the display is very laggy and in most of the cases not responsive. I tried everything: power cycle, update, couple of restart without success. Maybe it is a hardware issue?!

Most of the log is normal, but there are some wired logs for long response and variable name invalid.

Any ideas? 

<img width="724" alt="Bildschirmfoto 2023-12-09 um 23 18 52" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/62853417/65ab9b2f-dccf-43f0-ab31-d2281f28b3e5">
 
<img width="963" alt="Bildschirmfoto 2023-12-09 um 23 27 18" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/62853417/2b48b4ed-55c8-46fb-8a3a-15b266e1e634">

**Comment by edwardtfn** [comment]
This sequence of messages saying "invalid variable" are usually related t9nthe blueprint sending instructiin to a page when the page was already left. The common cause for this is some slowness on the Blueprint side (most likely) or on the Wi-Fi.
Haven't you seen any change on your host CPU/load or the temperature of CPU?
On the blur boot screen, which versions you see for TFT, ESPHome and Blueprint?

**Comment by geni0602** [comment]
I didn't change anything on my host and everything else home assistant 2023.12.1 and other containers are working fine. I've updated yesterday everything to 4.1.4 and my AP is in 1 m distance from the panel and there were no issues till know. My another 2 panels are also not affected. 
Wifi signal UnifiAP
![Screenshot_20231210-074047](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/62853417/74219d83-a960-4c3d-ab92-7433baf4265a)

**Comment by edwardtfn** [comment]
What is set on "Delay to avoid synchronisation problem"?

![IMG_6004](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/3cb3fde5-6900-441b-ba8b-f7ca2f92fce1)

And anything in the Home Assistant logs (Settings > System > Logs)?

**Comment by geni0602** [comment]
Delay is 1 millisecond. There are some errors in home assistant, but I am not sure if they are the reason for the problem. I power cycle the panel many times and it is also possible that some of the errors were created though my actions.

After restart of my Unifi Acess points in the morning everything is for know back to normal. My other panels were ok all the time. 



Log HA
Logger: homeassistant.components.automation.nspanel_wohnzi
Source: helpers/script.py:468
Integration: Automatisierung (documentation, issues)
First occurred: 9. Dezember 2023 um 22:47:37 (5 occurrences)
Last logged: 9. Dezember 2023 um 22:47:37

NSPanel wohnzi: Main choices: Climate - Sync: If at step 1: If at step 1: If at step 3: Error executing script. Unexpected error for call_service at pos 1: Not connected to nspanel_wohnzi @ 192.168.1.76!
NSPanel wohnzi: Main choices: Climate - Sync: If at step 1: If at step 1: Error executing script. Unexpected error for if at pos 3: Not connected to nspanel_wohnzi @ 192.168.1.76!
NSPanel wohnzi: Main choices: Climate - Sync: If at step 1: Error executing script. Unexpected error for if at pos 1: Not connected to nspanel_wohnzi @ 192.168.1.76!
NSPanel wohnzi: Main choices: Climate - Sync: Error executing script. Unexpected error for if at pos 1: Not connected to nspanel_wohnzi @ 192.168.1.76!
NSPanel wohnzi: Error executing script. Unexpected error for choose at pos 1: Not connected to nspanel_wohnzi @ 192.168.1.76!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/manager.py", line 746, in execute_service
    await entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 1185, in execute_service
    self._get_connection().send_message(req)
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 367, in _get_connection
    raise APIConnectionError(f"Not connected to {self.log_name}!")
aioesphomeapi.core.APIConnectionError: Not connected to nspanel_wohnzi @ 192.168.1.76!

**Comment by geni0602** [comment]
I will close this one for now. Everything ist back to normal. Thanks for your support @edwardtfn
