### ISSUE TITLE
After update ESPHOME 2023.12.0 Component ID disp1 was not declared to inherit from Component

### ISSUE THREAD

**Issue by carter013** [Blackymas/NSPanel_HA_Blueprint#1448]
Hello, After update esphome 2023.11.6 to 2023.12.0, my nspanel is in error for update

```log
INFO ESPHome 2023.12.0
INFO Reading configuration /config/esphome/nspanelsejour.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Reverting changes to https://github.com/Blackymas/NSPanel_HA_Blueprint@main -> f357a58b9ee9b88f2eead61f3e7a86264e020cc1
INFO Detected timezone 'Europe/Paris'
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1041, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1028, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 458, in command_run
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 192, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 204, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 679, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 184, in wrapped
    await coro(conf)
  File "/data/external_components/d28f7d73/esphome/components/nextion/display.py", line 106, in to_code
    await display.register_display(var, config)
  File "/esphome/esphome/components/display/__init__.py", line 119, in register_display
    await cg.register_component(var, config)
  File "/esphome/esphome/cpp_helpers.py", line 56, in register_component
    raise ValueError(
ValueError: Component ID disp1 was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.
```

My configuration YAML
```yaml
substitutions:

  device_name: nspanelsejour
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.13.150/nspanel_eu.tft"

  cooler_relay: "1"
  temp_units: "°C"
  temp_min: "16"
  temp_max: "30"
  temp_step: "0.5"
  
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml
      - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_advanced.yaml
    refresh: 300s
```
Am I the only one having this problem ?

**Comment by edwardtfn** [comment]
It isn't connected to the error message you shared, but the url for `nspanel_esphome_advanced.yaml` changed a while ago.

Please try this:
```yaml
substitutions:

  device_name: nspanelsejour
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.13.150/nspanel_eu.tft"

  cooler_relay: "1"
  temp_units: "°C"
  temp_min: "16"
  temp_max: "30"
  temp_step: "0.5"
  
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml
      - nspanel_esphome_addon_climate_cool.yaml
      - advanced/esphome/nspanel_esphome_advanced.yaml
    refresh: 300s
```

And before installing, please clean your build files.

**Comment by carter013** [comment]
It's perfect, thank you very much for the tip.
