### ISSUE TITLE
`DEV` It's difficult to select correct slider

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1531]
I tested on my climate control for tap water heating.  It's difficult to select correct slider. And it did not work either. HA logs.

```
Logger: homeassistant.components.automation.nspanel_livingroom
Source: helpers/script.py:468
Integration: Automation (documentation, issues)
First occurred: 08:51:44 (40 occurrences)
Last logged: 08:53:25

NSPanel Livingroom: Main choices: NSPanel event: Choose at step 2: NSPanel service call: If at step 1: Error executing script. Unexpected error for call_service at pos 1: 'temperature'
NSPanel Livingroom: Main choices: NSPanel event: Choose at step 2: NSPanel service call: Error executing script. Unexpected error for if at pos 1: 'temperature'
NSPanel Livingroom: Main choices: NSPanel event: Error executing script. Unexpected error for choose at pos 2: 'temperature'
NSPanel Livingroom: Error executing script. Unexpected error for choose at pos 2: 'temperature'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 632, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/thermiagenesis/climate.py", line 246, in async_set_temperature
    writes[self.meta[ATTR_TEMPERATURE]] = kwargs[ATTR_TEMPERATURE]
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'temperature'

```

Tap water attributes

```
hvac_modes:
  - "off"
  - auto
min_temp: 35
max_temp: 60
target_temp_step: 1
current_temperature: 51.8
target_temp_high: 60
target_temp_low: 43
hvac_action: idle
friendly_name: Tap water
supported_features: 2

```
And screenshot, where you also can see sliders are at wrong place.
![IMG_20240104_090405](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/238729/0abd0932-3cba-4a8e-a64d-f7c039623a34)

_Originally posted by @Floppe in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/909#issuecomment-1876547491_

**Comment by edwardtfn** [comment]
Could you please upgrade your system to v4.2dev.5 and try it again. All the 3 parts (TFT, ESPHome and Blueprint) must be updated. 😞 
I couldn't try myself, will try it tomorrow, but it would be nice if you can play with the system a bit and give some feedback (and logs, in case of errors).

**Comment by edwardtfn** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1510#issuecomment-1879967586

**Comment by Floppe** [comment]
Super. I'm still away today, but will test tomorrow.
