### ISSUE TITLE
`BUG` Button page becomes empty after updated from 4.2.1 to 4.2.2

### ISSUE THREAD

**Issue by shing6326** [Blackymas/NSPanel_HA_Blueprint#1649]
### TFT Version

4.2.2

### ESPHome Version

4.2.2

### Blueprint Version

4.2.2

### Panel Model

NSPanel EU Model

### What is the bug?

Button page becomes empty after updated from 4.2.1 to 4.2.2

### Steps to Reproduce

1. Swipe left to the buttonpage01 from homepage

### Your panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "sg_panel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: <masked>

  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/advanced/hmi/nspanel_CJK_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 0s

##### My customization - Start #####
esp32:
  framework:
    type: esp-idf

logger:
  #level: VERBOSE

api:
  encryption:
    key: ${api_key}

ota:
  password: !secret ota_password

wifi:
  use_address: <masked>
```

### ESPHome logs

```logs
[21:09:57][D][nextion:446]: Got touch event:
[21:09:57][D][nextion:447]:   page_id:      9
[21:09:57][D][nextion:448]:   component_id: 4
[21:09:57][D][nextion:449]:   event type:   PRESS
[21:09:57][D][nextion:464]: Got new page: 0
[21:09:57][D][display.disp1.on_page:717]: Nextion page changed
[21:09:57][D][display.disp1.on_page:718]: New page: home (0)
[21:09:57][D][text_sensor:064]: 'sg_panel Current page': Sending state 'home'
[21:09:57][D][text_sensor:064]: 'sg_panel Detailed Entity': Sending state ''
[21:09:57][D][script.page_changed:2094]: New page: home
[21:09:57][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[21:09:57][D][script.timer_dim:2909]: Waking up on page: home
[21:09:57][D][script.set_brightness:2482]: brightness: 43%
[21:09:57][C][homeassistant.time:010]: Home Assistant Time:
[21:09:57][C][homeassistant.time:011]:   Timezone: '<+08>-8'
[21:09:57][D][sensor:094]: 'sg_panel Page Id': Sending state 0.00000  with 2 decimals of accuracy
[21:09:57][D][sensor.page_id:1367]: New page Id: 0
[21:09:57][C][status:034]: Status Binary Sensor 'sg_panel Status'
[21:09:57][C][status:034]:   Device Class: 'connectivity'
[21:09:59][C][mdns:115]: mDNS:
[21:09:59][C][mdns:116]:   Hostname: sg_panel
[21:09:59][C][ota:097]: Over-The-Air Updates:
[21:09:59][C][ota:098]:   Address: 10.186.9.115:3232
[21:09:59][C][ota:101]:   Using Password.
[21:09:59][C][api:139]: API Server:
[21:09:59][C][api:140]:   Address: 10.186.9.115:6053
[21:09:59][C][api:142]:   Using noise encryption: YES
[21:09:59][C][wifi_signal.sensor:009]: WiFi Signal 'sg_panel RSSI'
[21:09:59][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[21:09:59][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[21:09:59][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[21:09:59][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[21:09:59][D][nextion:446]: Got touch event:
[21:09:59][D][nextion:447]:   page_id:      0
[21:09:59][D][nextion:448]:   component_id: 0
[21:09:59][D][nextion:449]:   event type:   PRESS
[21:09:59][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[21:09:59][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[21:10:00][D][nextion:446]: Got touch event:
[21:10:00][D][nextion:447]:   page_id:      0
[21:10:00][D][nextion:448]:   component_id: 0
[21:10:00][D][nextion:449]:   event type:   RELEASE
[21:10:00][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[21:10:00][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[21:10:00][D][nextion:464]: Got new page: 12
[21:10:00][D][display.disp1.on_page:717]: Nextion page changed
[21:10:00][D][display.disp1.on_page:718]: New page: buttonpage01 (12)
[21:10:00][D][text_sensor:064]: 'sg_panel Current page': Sending state 'buttonpage01'
[21:10:00][D][text_sensor:064]: 'sg_panel Detailed Entity': Sending state ''
[21:10:00][D][script.page_changed:2094]: New page: buttonpage01
[21:10:00][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[21:10:00][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[21:10:00][D][sensor:094]: 'sg_panel Page Id': Sending state 12.00000  with 2 decimals of accuracy
[21:10:00][D][sensor.page_id:1367]: New page Id: 12
[21:10:00][W][component:214]: Component display took a long time for an operation (0.05 s).
[21:10:00][W][component:215]: Components should block for at most 20-30ms.
[21:10:03][D][sensor:094]: 'ntc_source': Sending state 1.43200 V with 2 decimals of accuracy
[21:10:03][D][resistance:039]: 'resistance_sensor' - Resistance 8585.9Ω
[21:10:03][D][sensor:094]: 'resistance_sensor': Sending state 8585.86816 Ω with 1 decimals of accuracy
[21:10:03][D][ntc:026]: 'sg_panel Temperature' - Temperature: 28.5°C
[21:10:03][D][sensor:094]: 'sg_panel Temperature': Sending state 28.47117 °C with 1 decimals of accuracy
[21:10:10][I][addon_upload_tft.script.report_settings:178]: TFT URL: https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/advanced/hmi/nspanel_CJK_eu.tft
[21:10:10][I][addon_upload_tft.script.report_settings:179]: Substitutions:
[21:10:10][I][addon_upload_tft.script.report_settings:180]:   nextion_update_url:        https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/advanced/hmi/nspanel_CJK_eu.tft
[21:10:10][I][addon_upload_tft.script.report_settings:181]:   nextion_update_base_url:   https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/
[21:10:10][I][addon_upload_tft.script.report_settings:182]:   upload_tft_chunk_size_max: 32768
[21:10:10][I][addon_upload_tft.script.report_settings:183]:   upload_tft_baud_rate:      921600
```

### Home Assistant logs

```logs
2024-01-16 20:55:27.687 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 7: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:55:27.689 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: Error executing script. Error rendering template for if at pos 7: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:55:27.689 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: NSPanel event: Choose at step 2: Page changed: Error executing script. Error rendering template for choose at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:55:27.690 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: NSPanel event: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:55:27.692 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:55:27.693 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:55:58.893 ERROR (MainThread) [homeassistant.helpers.entity] Failed to set state for sensor.ir_remote_learned_ir_code, fall back to unknown
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1129, in _async_write_ha_state
hass.states.async_set(
File "/usr/src/homeassistant/homeassistant/core.py", line 1807, in async_set
state = State(
^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 1384, in __init__
validate_state(state)
File "/usr/src/homeassistant/homeassistant/core.py", line 204, in validate_state
raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state with length 420. State max length is 255 characters.
2024-01-16 20:55:59.062 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: Climate - Sync: If at step 1: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:55:59.063 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: Climate - Sync: Error executing script. Error rendering template for if at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:55:59.063 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:55:59.065 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:02.544 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: Climate - Sync: If at step 1: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:02.545 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: Climate - Sync: Error executing script. Error rendering template for if at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:02.546 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:02.546 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:24.294 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: Climate - Sync: If at step 1: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:24.297 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: Climate - Sync: If at step 1: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:24.297 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: Climate - Sync: Error executing script. Error rendering template for if at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:24.297 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: Climate - Sync: Error executing script. Error rendering template for if at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:24.297 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:24.299 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:24.299 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:24.300 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:25.236 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Button pages: If at step 2: Repeat at step 6: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:25.237 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Button pages: If at step 2: Error executing script. Error rendering template for repeat at pos 6: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:25.237 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Button pages: Error executing script. Error rendering template for if at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:25.237 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: NSPanel event: Choose at step 2: Page changed: Error executing script. Error rendering template for choose at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:25.237 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Main choices: NSPanel event: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:25.237 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel backup: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-16 20:56:25.238 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable
```

**Comment by edwardtfn** [comment]
@shing6326, I wanna work at this with top priority, but I will need some additional information to be able to replicate this issue.

1. Could you please share the type of entities used on button page 1 and it's attributes (from Developer Tools > States tab). I know this is quite a lot of work to capture. 😞 
2. What about the other button pages? Do you have the same issue on all 4 pages?

**Comment by edwardtfn** [comment]
I can see in your logs that the same error happens when syncing the climate entity, so could you please start sharing the state and attributes of that entity?

**Comment by shing6326** [comment]
@edwardtfn really appreciated 
```
entity01
Entity: climate.bedroom_ac
Name: Bedroom AC
State: off
Attributes:
hvac_modes: auto, cool, dry, fan_only, heat, off
min_temp: 7
max_temp: 35
target_temp_step: 1
fan_modes: auto, low, medium, high
swing_modes: on, off, vertical, horizontal
current_temperature: 28.4
temperature: 26
fan_mode: low
swing_mode: off
friendly_name: Bedroom AC
supported_features: 41

entity02
Entity: fan.ceiling_fan
Name: ceiling fan
Attributes:
State: off
preset_modes: null
percentage: 0
percentage_step: 11.11111111111111
preset_mode: null
last_on_speed: 2
device_code: 1999
manufacturer: KDK
supported_models: K12UX
supported_controller: MQTT
commands_encoding: Raw
icon: mdi:ceiling-fan
friendly_name: ceiling fan
supported_features: 1

entity03
Entity: fan.lemo_fw2_1c21ab_lemo_fw2_1c21ab
Name: Lemo FW2 1c21ab
State: on
Attributes:
preset_modes: 
oscillating: false
percentage: 25
percentage_step: 25
preset_mode: 
friendly_name: Lemo FW2 1c21ab 
supported_features: 3

entity04
Entity: light.table_lamp
Name: Table Lamp
State: off
Attributes:
min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
effect_list: blink, breathe, okay, channel_change, candle, fireplace, colorloop, finish_effect, stop_effect, stop_hue_effect
supported_color_modes: color_temp, xy
icon: hue:go-portable-table-alt
friendly_name: Table Lamp
supported_features: 44
color: 
h: 23
hue: 23
s: 0
saturation: 0
x: 0.3232
'y': 0.3292
color_temp_startup: 65535
linkquality: 145
power_on_behavior: previous
update: 
installed_version: 16785412
latest_version: 16785412
state: idle
update_available: false
color_mode: null
brightness: null
hs_color: null
rgb_color: null
xy_color: null

entity05
Entity: media_player.bedroom_tv_2
Name: Bedroom TV
State: off
Attributes:
assumed_state: true
device_class: tv
friendly_name: Bedroom  TV
supported_features: 22457

**Comment by shing6326** [comment]
I only have 5 entities so didn't test to the page 2-4. 
Some updates. After removed the entity01, all the buttons show up 💯

**Comment by edwardtfn** [comment]
> Some updates. After removed the entity01, all the buttons show up 💯

Great! So it narrows down to the climate entity.
I will try to duplicate this here and come back to you later.

**Comment by edwardtfn** [comment]
Do you have a custom icon or color set for at entity in the Blueprint settings?

**Comment by edwardtfn** [comment]
I believe I have a fix for this on `dev`.

**Comment by shing6326** [comment]
Hi @edwardtfn , it works perfectly after I replaced the blueprint from dev branch!!

**Comment by edwardtfn** [comment]
This was fixed on ESPHome v4.2.2. Are you sure you have that version?

**Comment by djsomi** [comment]
Same here, 4.2.1 > 4.2.2 killed homepage sensors and climate for me also!

**Comment by edwardtfn** [comment]
Could you please share the attributes of your climate entity?

**Comment by andythomas** [comment]
This seems to be related to #1655

**Comment by djsomi** [comment]
Sure, on some panels randomly C02 appears, and also affected these entities in climate.

climate.dolgozo

hvac_modes: off, heat
min_temp: 5
max_temp: 30
preset_modes: none, temporary, permanent
current_temperature: 22.5
temperature: 19
preset_mode: permanent
status: 
setpoints:
  this_sp_from: '2024-01-16T07:00:00+01:00'
  this_sp_temp: 21
  next_sp_from: '2024-01-17T07:00:00+01:00'
  next_sp_temp: 21
zone_id: '2460001'
active_faults: []
setpoint_status:
  target_heat_temperature: 19
  setpoint_mode: PermanentOverride
temperature_status:
  temperature: 22.5
  is_available: true

friendly_name: Dolgozo Futes
supported_features: 17

sensor.netatmo_workroom_co2

state_class: measurement
unit_of_measurement: ppm
attribution: Data provided by Netatmo
device_class: carbon_dioxide
friendly_name: Dolgozo CO2

sensor.netatmo_workroom_humidity

state_class: measurement
unit_of_measurement: %
attribution: Data provided by Netatmo
device_class: humidity
friendly_name: Dolgozo Humidity

**Comment by edwardtfn** [comment]
Thanks!
I believe the version currently in `dev` will fix this issue.
Anyone available to try `dev`?

**Comment by djsomi** [comment]
Tomorrow I'll give a try!

**Comment by edwardtfn** [comment]
Probably related:
- #1649 
- #1655
- #1656 

There's a fix for this in `dev`. Please let me know if you have a chance to try that, so I can proceed to the release.

**Comment by shing6326** [comment]
hi @edwardtfn , could you point me which commit solves the climate issue? The 071a130 fixes the buttonpage issue but doesn't help on the climate page icon missing. thanks
https://github.com/Blackymas/NSPanel_HA_Blueprint/compare/main...dev

**Comment by edwardtfn** [comment]
Mmmm.
I was expecting that one (https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/071a13076fae2cd14c3f0885302c4b83369a76a8) to be fixing this issue.

Could you please share updated Home Assistant logs (Settings > System > Logs)?

**Comment by shing6326** [comment]
here is the log 

```2024-01-17 08:48:53.368 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Climate page: If at step 6: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:53.369 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Climate page: Error executing script. Error rendering template for if at pos 6: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:53.369 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Error executing script. Error rendering template for choose at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:53.369 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:53.369 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:53.370 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:57.170 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Climate page: If at step 6: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:57.170 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Climate page: Error executing script. Error rendering template for if at pos 6: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:57.170 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Error executing script. Error rendering template for choose at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:57.170 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:57.171 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:48:57.171 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:09.808 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Climate page: If at step 6: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:09.808 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Climate page: Error executing script. Error rendering template for if at pos 6: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:09.809 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Error executing script. Error rendering template for choose at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:09.809 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:09.809 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:09.810 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:11.970 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: Climate - Sync: If at step 2: If at step 2: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:11.973 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: Climate - Sync: If at step 2: Error executing script. Error rendering template for if at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:11.976 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: Buttons entity updated: Choose at step 1: Climate page: If at step 6: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:11.977 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: Climate - Sync: Error executing script. Error rendering template for if at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:11.978 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: Buttons entity updated: Choose at step 1: Climate page: Error executing script. Error rendering template for if at pos 6: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:11.979 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:11.979 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:11.980 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: Buttons entity updated: Error executing script. Error rendering template for choose at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:11.980 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 08:49:11.981 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable

**Comment by edwardtfn** [comment]
Could you please try with the latest version on `dev` (just modified by https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/52b65d15367777f7336c468b7c65d67b025ab50a)?

I cannot run tests from my side right now, so I would appreciate if you let me know not only for this issue here, but if you find anything else I could have broken with this change.

**Comment by shing6326** [comment]
Hi @edwardtfn , I can only test it after 6pm SGT, I will share you the result after the update. Sorry about that

**Comment by edwardtfn** [comment]
No need to apologise. 😉

**Comment by shing6326** [comment]
Hi @edwardtfn , I have applied the patch and still cannot show the climate page properly. Below is the system logs after the update.
```
2024-01-17 19:04:02.988 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Climate page: If at step 6: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 19:04:02.988 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Climate page: Error executing script. Error rendering template for if at pos 6: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 19:04:02.989 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Choose at step 2: Page changed: Error executing script. Error rendering template for choose at pos 1: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 19:04:02.989 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Main choices: NSPanel event: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 19:04:02.989 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] SG Panel: Error executing script. Error rendering template for choose at pos 2: TypeError: argument of type 'NoneType' is not iterable
2024-01-17 19:04:02.990 ERROR (MainThread) [homeassistant.components.automation.sg_nspanel] Error while executing automation automation.sg_nspanel: TypeError: argument of type 'NoneType' is not iterable

**Comment by shing6326** [comment]
hi @edwardtfn , I am able to fix it by the following modification

```diff --git a/nspanel_blueprint.yaml b/nspanel_blueprint.yaml
index a7f5457..2b0a7c4 100644
--- a/nspanel_blueprint.yaml
+++ b/nspanel_blueprint.yaml
@@ -9060,7 +9060,7 @@ action:
                                   max_temp: '{{ (max_temp_raw / temp_step) | round * temp_step }}'
                                   total_steps: '{{ ((max_temp-temp_offset)/temp_step) | round(0) | int }}'
                                   climate_state: '{{ states(climate_entity) | default("unavailable") if climate_entity is string else "unavailable" }}'
-                                  hvac_action: '{{ state_attr(climate_entity, "hvac_action") }}'
+                                  hvac_action: '{{ state_attr(climate_entity, "hvac_action")  | default("") }}'
                                   hvac_modes: '{{ state_attr(climate_entity, "hvac_modes") }}'
                                   climate_action: '{{ hvac_action if hvac_action and hvac_action not in enum.states.unknown else climate_state }}'
                                   climate_icon: >

**Comment by shing6326** [comment]
the below modification also fix the climate auto mode icon and color

```
diff --git a/nspanel_blueprint.yaml b/nspanel_blueprint.yaml
index a7f5457..33f874e 100644
--- a/nspanel_blueprint.yaml
+++ b/nspanel_blueprint.yaml
@@ -7394,7 +7394,7 @@ action:
                 {% elif "drying" in entity_climate_action or "dry" in entity_climate_action %}{{ nextion.color.orange }}
                 {% elif "fan" in entity_climate_action or "fan_only" in entity_climate_action %}{{ nextion.color.cyan }}
                 {% elif "heat_cool" in entity_climate_action %}{{ nextion.color.amber }}
-                {% elif "auto" in entity_climate_action %}{{ nextion.color.off }}
+                {% elif "auto" in entity_climate_action %}{{ nextion.color.green }}
                 {% elif "idle" in entity_climate_action %}{{ nextion.color.off }}
                 {% else %}{{ entity_icon_color }}
                 {% endif %}
@@ -9060,7 +9060,7 @@ action:
                                   max_temp: '{{ (max_temp_raw / temp_step) | round * temp_step }}'
                                   total_steps: '{{ ((max_temp-temp_offset)/temp_step) | round(0) | int }}'
                                   climate_state: '{{ states(climate_entity) | default("unavailable") if climate_entity is string else "unavailable" }}'
-                                  hvac_action: '{{ state_attr(climate_entity, "hvac_action") }}'
+                                  hvac_action: '{{ state_attr(climate_entity, "hvac_action")  | default("") }}'
                                   hvac_modes: '{{ state_attr(climate_entity, "hvac_modes") }}'
                                   climate_action: '{{ hvac_action if hvac_action and hvac_action not in enum.states.unknown else climate_state }}'
                                   climate_icon: >
@@ -9070,7 +9070,7 @@ action:
                                     {% elif "drying" in climate_action or "dry" in climate_action %}{{ all_icons["water-percent"] }}
                                     {% elif "fan" in climate_action or "fan_only" in climate_action %}{{ all_icons.fan }}
                                     {% elif "heat_cool" in climate_action %}{{ all_icons.autorenew }}
-                                    {% elif "auto" in climate_action %}{{ all_icons.blank }}
+                                    {% elif "auto" in climate_action %}{{ all_icons["calendar-sync"] }}
                                     {% elif "idle" in climate_action %}{{ all_icons.thermometer }}
                                     {% else %}{{ all_icons.blank }}
                                     {% endif %}

**Comment by edwardtfn** [comment]
Nice!
I will take a look, but always feel free to create a PR. 😉

**Comment by edwardtfn** [comment]
`dev` is updated with the changes you proposed and some other things from my side. Please let me know if it is all working fine with you.

**Comment by shing6326** [comment]
Hi @edwardtfn, it works like a charm, thank you

**Comment by edwardtfn** [comment]
Thank you for your support on finding the issue.

**Comment by edwardtfn** [comment]
v4.2.3 was released.
Please let me know if that was fixed, otherwise we can reopen this.

**Comment by djsomi** [comment]
Looks good for me!

**Comment by djsomi** [comment]
Climate and related entites working now, but device is bricked if I enable BT proxy.

Had to remove BT proxy and re-flash by wire. What is going on?

**Comment by edwardtfn** [comment]
I will have to run some tests, but I can say I've some of my devices running `bluetooth_proxy` with no issues.
Could you please report this in another issue and share your yaml so I can try to duplicate it?
