### ISSUE TITLE
Cannot update firmware 

### ISSUE THREAD

**Issue by barrylapthorne** [Blackymas/NSPanel_HA_Blueprint#2158]
### TFT Version

4.3.7

### ESPHome Version

4.3.7

### Blueprint Version

4.3.7

### Panel Model

US

### What is the bug?

When trying to update firmware it indicates to me that there is a capital ‘N’ when there is not 
![IMG_6634](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/82895068/c6000022-fb3d-4377-ac1c-ae3c185b2b02)
![IMG_6635](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/82895068/020698f4-26b6-497d-a637-3e3225ff3c55)
![IMG_6636](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/82895068/a380da65-81b8-440b-a11f-d870390fae70)

**Comment by edwardtfn** [comment]
Looks like in your substitutions, the items are missing the two blank spaces at the beginning. (First picture)
Could you please share your yaml as a text and not screenshot, so we can cooy/paste to duplicate the issue?

**Comment by smarthomefamilyverrips** [comment]
@edwardtfn after update to ESPhome 2024.6.1 I get the following in my logs when I try to view logs

INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/nsbathroom.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1079, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1057, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1093, in read_config
    res = load_config(command_line_substitutions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 947, in load_config
    return _load_config(command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 937, in _load_config
    return validate_config(config, command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 774, in validate_config
    config = do_packages_pass(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/components/packages/__init__.py", line 179, in do_packages_pass
    recursive_package = do_packages_pass(package_config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/components/packages/__init__.py", line 179, in do_packages_pass
    recursive_package = do_packages_pass(package_config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/components/packages/__init__.py", line 180, in do_packages_pass
    config = merge_config(recursive_package, config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config_helpers.py", line 101, in merge_config
    return merge(full_old, full_new)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config_helpers.py", line 52, in merge
    res[k] = merge(old[k], v) if k in old else v
             ^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config_helpers.py", line 52, in merge
    res[k] = merge(old[k], v) if k in old else v
             ^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config_helpers.py", line 52, in merge
    res[k] = merge(old[k], v) if k in old else v
             ^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config_helpers.py", line 58, in merge
    ids = {
          ^
  File "/esphome/esphome/config_helpers.py", line 61, in <dictcomp>
    if (v_id := v.get(CONF_ID)) and isinstance(v_id, str)
                ^^^^^
AttributeError: 'EStr' object has no attribute 'get'

**Comment by smarthomefamilyverrips** [comment]
@edwardtfn I did see that there is a fix for this error AttributeError: 'EStr' object has no attribute 'get' in the form of update v4.3.9 but I am still on v4.3.7 and I not did do the HA update to version 2024.6.X so i can not update to v4.3.9 .... so how I can fix this if I wanna stay on v4.3.7 ???

**Comment by edwardtfn** [comment]
You can update only ESPHome part to v4.3.9.and stay with Blueprint v4.3.7. It should work.with no issues.

**Comment by smarthomefamilyverrips** [comment]
> You can update only ESPHome part to v4.3.9.and stay with Blueprint v4.3.7. It should work with no issues.

@edwardtfn So i can just use the update button on the ESPhome interface even when I am still on HA version 2024.5.5?

**Comment by edwardtfn** [comment]
Yes. Or you can do `ref: v4.3.9`.

**Comment by edwardtfn** [comment]
- #2152

**Comment by smarthomefamilyverrips** [comment]
Thanks @edwardtfn !!! 🥇

**Comment by edwardtfn** [comment]
@barrylapthorne, are you still having issues to compile your firmware?

**Comment by barrylapthorne** [comment]
Good day. 

Yes I am still having issues. I do not have a flash tool so I cannot even reflash it to the latest. It’s frustrating me
