### ISSUE TITLE
V3.3 stopped working for one of the nspanel

### ISSUE THREAD

**Issue by hkr086** [Blackymas/NSPanel_HA_Blueprint#954]
Logger: homeassistant.components.automation.nspanelkitchen
Source: components/esphome/__init__.py:622
Integration: Automation (documentation, issues)
First occurred: July 28, 2023 at 9:00:35 PM (324 occurrences)
Last logged: 8:15:56 AM

nspanelkitchen: Error executing script. Unexpected error for choose at pos 1: Not connected to nspanelkitchen @ 192.168.11.19!
While executing automation automation.nspanelkitchen
nspanelkitchen: Main choices: Climate - Sync: Error executing script. Unexpected error for call_service at pos 2: Not connected to nspanelkitchen @ 192.168.11.19!
Nspanelkitchen: Main choices: Boot init: Error executing script. Unexpected error for call_service at pos 2: Not connected to nspanelkitchen @ 192.168.11.19!
Nspanelkitchen: Error executing script. Unexpected error for choose at pos 1: Not connected to nspanelkitchen @ 192.168.11.19!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1957, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1997, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 622, in execute_service
    await entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 1260, in execute_service
    self._check_authenticated()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 328, in _check_authenticated
    self._check_connected()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 320, in _check_connected
    raise APIConnectionError(f"Not connected to {self._log_name}!")
aioesphomeapi.core.APIConnectionError: Not connected to nspanelkitchen @ 192.168.11.19!

**Comment by edwardtfn** [comment]
> nspanelkitchen: Error executing script. Unexpected error for choose at pos 1: Not connected to nspanelkitchen @ 192.168.11.19!

Looks like the issue is on the panel connection to Home Assistant. Maybe a weak Wi-Fi signal at that panel?

**Comment by hkr086** [comment]
Hi, I will check , but did not understand what the 192.168.11.19 is referred to in this error. It's not the home assistant as the assistant is 11.10 and the panel itself is also another IP. Wifi on the panel is 68db which I think should be fine?

**Comment by hkr086** [comment]
So the 192.168.11.19 should be ha ip?

**Comment by hkr086** [comment]
So the 192.168.11.19 should be ha ip?

**Comment by edwardtfn** [comment]
Home Assistant is trying to connect to your panel on that IP.
Try to remove the panel from Home Assistant (Settings > Devices and Services > ESPHome) and then add it back.

**Comment by hkr086** [comment]
Your great.That was it!  Thank you sir
