### ISSUE TITLE
Problem: No entities are loaded (  Loading on home page )

### ISSUE THREAD

**Issue by plhy** [Blackymas/NSPanel_HA_Blueprint#983]
Hello,

I have a problem: after turning on the panel, no entity is loaded. The panel is in the "loading" state, no change will be reflected. I managed to get one entity on the first page but it is not responding. I tried deleting the automation and then the blueprint. I re-integrated the blueprint and created a new automation. Nothing works. Update TFT display, restart, Exit reparse: nothing helps. ESP responds (restart can be triggered, TFT update, relay clicks.) Please help. thank you very much
  
![ns](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/72349207/4b4973b6-bd15-4bca-8e56-b11e4b471107)

In the HA log I found:

```
Logger: aioesphomeapi.connection
Source: runner.py:179
First occurred: 14:14:45 (8 occurrences)
Last logged: 15:18:00

nsobyvak @ 192.168.1.55: Connection error occurred: [Errno 104] Connection reset by peer
```

AND:
```
Logger: homeassistant.components.automation.nspanel_configuration
Source: components/esphome/manager.py:649
Integration: Automation (documentation, issues)
First occurred: 14:41:00 (12 occurrences)
Last logged: 15:18:01

NSPanel Configuration: Main choices: Date & Time: If at step 1: Error executing script. Unexpected error for call_service at pos 5: Authenticated connection not ready yet for nsobyvak @ 192.168.1.55; current state is ConnectionState.INITIALIZED!
NSPanel Configuration: Main choices: Date & Time: Error executing script. Unexpected error for if at pos 1: Authenticated connection not ready yet for nsobyvak @ 192.168.1.55; current state is ConnectionState.INITIALIZED!
NSPanel Configuration: Error executing script. Unexpected error for choose at pos 1: Authenticated connection not ready yet for nsobyvak @ 192.168.1.55; current state is ConnectionState.INITIALIZED!
While executing automation automation.nspanel_configuration
NSPanel Configuration: Main choices: Date & Time: If at step 1: Error executing script. Unexpected error for call_service at pos 7: Authenticated connection not ready yet for nsobyvak @ 192.168.1.55; current state is ConnectionState.INITIALIZED!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/manager.py", line 649, in execute_service
    await entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 1287, in execute_service
    self._check_authenticated()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 307, in _check_authenticated
    raise APIConnectionError(
aioesphomeapi.core.APIConnectionError: Authenticated connection not ready yet for nsobyvak @ 192.168.1.55; current state is ConnectionState.INITIALIZED!
```

The ESPhome log does not write any errors.
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/72349207/3f7ab623-19b4-46ed-aa82-969b92a3def4)

**Comment by plhy** [comment]
Should I add some screens from "traces" or? Can someone please respond? I do not know what to do.

**Comment by edwardtfn** [comment]
Sorry for the late replay here.
In order to understand better what you have right now, please look at the boot page (restart your panel) which versions are shown for TFT, ESPHome and Blueprint?

**Comment by edwardtfn** [comment]
Your log says the panel is not properly connected to Home Assistant.
1. Are you using the standard ESPHome yaml setting or have you added any customization? In this case, could you please share your ESPHome yaml settings? Please remove any sensitive information before sharing.
2. You can try removing your device from Home Assistant (Settings > Devices and Services > ESPHome) and then add it again.

**Comment by plhy** [comment]
![Uploading IMG_4298.jpeg…]()

**Comment by plhy** [comment]
![IMG_4298](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/72349207/e4d79f14-ed31-4f86-a2f4-ad1edd1e293b)

**Comment by edwardtfn** [comment]
Ok, you have to update your TFT to v3.4.
Make sure to download the latest version from GitHub to your local server before clicking on "Upload TFT" button.

**Comment by plhy** [comment]
I downloaded the file you shared (I don't see a newer one on github, 2 months ago). Version on panel still 3.3. I uploaded the file to "/config/www" folder. I deleted the old file before. After uploading I restarted HA and clicked "Update TFT display". Still 3.3

**Comment by edwardtfn** [comment]
Could you please share the ESPHome logs from right before you click on "Upload TFT" to the moment the panel restarts? As it is failing, this shouldn't be more than a few seconds.

**Comment by plhy** [comment]
Here log:

```
INFO ESPHome 2023.8.1
INFO Reading configuration /config/esphome/nsobyvak.yaml...
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Starting log output from nsobyvak.local using esphome API
INFO Successfully connected to nsobyvak.local
[13:09:48][I][app:102]: ESPHome version 2023.8.1 compiled on Aug 18 2023, 12:59:29
[13:09:48][C][wifi:543]: WiFi:
[13:09:48][C][wifi:379]:   Local MAC: 3C:E9:0E:87:BE:80
[13:09:48][C][wifi:380]:   SSID: [redacted]
[13:09:48][C][wifi:381]:   IP Address: 192.168.1.55
[13:09:48][C][wifi:383]:   BSSID: [redacted]
[13:09:48][C][wifi:384]:   Hostname: 'nsobyvak'
[13:09:48][C][wifi:386]:   Signal strength: -60 dB ▂▄▆█
[13:09:48][C][wifi:390]:   Channel: 10
[13:09:48][C][wifi:391]:   Subnet: 255.255.255.0
[13:09:48][C][wifi:392]:   Gateway: 192.168.1.1
[13:09:48][C][wifi:393]:   DNS1: 192.168.1.1
[13:09:48][C][wifi:394]:   DNS2: 0.0.0.0
[13:09:48][C][logger:301]: Logger:
[13:09:48][C][logger:302]:   Level: DEBUG
[13:09:48][C][logger:303]:   Log Baud Rate: 0
[13:09:48][C][logger:305]:   Hardware UART: UART0
[13:09:48][C][uart.arduino_esp32:124]: UART Bus 0:
[13:09:48][C][uart.arduino_esp32:125]:   TX Pin: GPIO16
[13:09:48][C][uart.arduino_esp32:126]:   RX Pin: GPIO17
[13:09:48][C][uart.arduino_esp32:128]:   RX Buffer Size: 256
[13:09:48][C][uart.arduino_esp32:130]:   Baud Rate: 115200 baud
[13:09:48][C][uart.arduino_esp32:131]:   Data Bits: 8
[13:09:48][C][uart.arduino_esp32:132]:   Parity: NONE
[13:09:48][C][uart.arduino_esp32:133]:   Stop bits: 1
[13:09:48][C][ledc.output:164]: LEDC Output:
[13:09:48][C][ledc.output:165]:   Pin GPIO21
[13:09:48][C][ledc.output:166]:   LEDC Channel: 0
[13:09:48][C][ledc.output:167]:   PWM Frequency: 1000.0 Hz
[13:09:48][C][ledc.output:168]:   Bit depth: 16
[13:09:48][C][template.binary_sensor:028]: Template Binary Sensor 'nsobyvak Nextion display'
[13:09:48][C][template.binary_sensor:028]:   Device Class: 'connectivity'
[13:09:48][C][uptime.sensor:031]: Uptime Sensor 'nsobyvak uptime'
[13:09:48][C][uptime.sensor:031]:   Device Class: 'duration'
[13:09:48][C][uptime.sensor:031]:   State Class: 'total_increasing'
[13:09:48][C][uptime.sensor:031]:   Unit of Measurement: 's'
[13:09:48][C][uptime.sensor:031]:   Accuracy Decimals: 0
[13:09:48][C][uptime.sensor:031]:   Icon: 'mdi:timer-outline'
[13:09:48][C][template.text_sensor:020]: Template Sensor 'nsobyvak Notification Label'
[13:09:48][C][template.text_sensor:020]: Template Sensor 'nsobyvak Notification Text'
[13:09:48][C][template.text_sensor:020]: Template Sensor 'nsobyvak Settings Entity'
[13:09:48][C][switch.gpio:068]: GPIO Switch 'nsobyvak Relay 1'
[13:09:48][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[13:09:48][C][switch.gpio:031]:   Pin: GPIO22
[13:09:48][C][switch.gpio:068]: GPIO Switch 'nsobyvak Relay 2'
[13:09:48][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[13:09:48][C][switch.gpio:031]:   Pin: GPIO19
[13:09:48][C][switch.gpio:068]: GPIO Switch 'nsobyvak Screen Power'
[13:09:48][C][switch.gpio:091]:   Restore Mode: always ON
[13:09:48][C][switch.gpio:031]:   Pin: GPIO4
[13:09:48][I][ota:113]: Boot seems successful, resetting boot loop counter.
[13:09:48][D][esp32.preferences:114]: Saving 1 preferences to flash...
[13:09:48][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[13:09:48][C][template.number:050]: Template Number 'nsobyvak Display Brightness'
[13:09:48][C][template.number:050]:   Unit of Measurement: '%'
[13:09:48][C][template.number:051]:   Optimistic: YES
[13:09:48][C][template.number:052]:   Update Interval: 60.0s
[13:09:48][C][template.number:050]: Template Number 'nsobyvak Display Brightness Dimdown'
[13:09:48][C][template.number:050]:   Unit of Measurement: '%'
[13:09:48][C][template.number:051]:   Optimistic: YES
[13:09:48][C][template.number:052]:   Update Interval: 60.0s
[13:09:48][C][template.number:050]: Template Number 'nsobyvak Temperature Correction'
[13:09:48][C][template.number:050]:   Unit of Measurement: '°C'
[13:09:48][C][template.number:051]:   Optimistic: YES
[13:09:48][C][template.number:052]:   Update Interval: 60.0s
[13:09:48][C][template.number:050]: Template Number 'nsobyvak Page Timeout'
[13:09:48][C][template.number:051]:   Optimistic: YES
[13:09:48][C][template.number:052]:   Update Interval: 60.0s
[13:09:48][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'nsobyvak Left Button'
[13:09:48][C][gpio.binary_sensor:016]:   Pin: GPIO14
[13:09:48][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'nsobyvak Right Button'
[13:09:48][C][gpio.binary_sensor:016]:   Pin: GPIO27
[13:09:49][C][template.switch:068]: Template Switch 'nsobyvak Notification unread'
[13:09:49][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[13:09:49][C][template.switch:057]:   Optimistic: YES
[13:09:49][C][template.switch:068]: Template Switch 'nsobyvak Notification sound'
[13:09:49][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[13:09:49][C][template.switch:057]:   Optimistic: YES
[13:09:49][C][template.switch:068]: Template Switch 'nsobyvak Confirmation Message'
[13:09:49][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[13:09:49][C][template.switch:057]:   Optimistic: YES
[13:09:49][C][template.switch:068]: Template Switch 'nsobyvak Sleep mode'
[13:09:49][C][template.switch:079]:   Device Class: 'switch'
[13:09:49][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[13:09:49][C][template.switch:057]:   Optimistic: NO
[13:09:49][C][template.switch:068]: Template Switch 'nsobyvak Relay 1 Local Fallback'
[13:09:49][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[13:09:49][C][template.switch:057]:   Optimistic: YES
[13:09:49][C][template.switch:068]: Template Switch 'nsobyvak Relay 2 Local Fallback'
[13:09:49][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[13:09:49][C][template.switch:057]:   Optimistic: YES
[13:09:49][C][rtttl:018]: Rtttl
[13:09:49][C][restart.button:017]: Restart Button 'nsobyvak Restart'
[13:09:49][C][status:034]: Status Binary Sensor 'nsobyvak Status'
[13:09:49][C][status:034]:   Device Class: 'connectivity'
[13:09:49][C][adc:094]: ADC Sensor 'ntc_source'
[13:09:49][C][adc:094]:   Device Class: 'voltage'
[13:09:49][C][adc:094]:   State Class: 'measurement'
[13:09:49][C][adc:094]:   Unit of Measurement: 'V'
[13:09:49][C][adc:094]:   Accuracy Decimals: 2
[13:09:49][C][adc:104]:   Pin: GPIO38
[13:09:49][C][adc:119]:  Attenuation: 11db
[13:09:49][C][adc:133]:   Update Interval: 60.0s
[13:09:49][C][resistance:010]: Resistance Sensor 'resistance_sensor'
[13:09:49][C][resistance:010]:   State Class: 'measurement'
[13:09:49][C][resistance:010]:   Unit of Measurement: 'Ω'
[13:09:49][C][resistance:010]:   Accuracy Decimals: 1
[13:09:49][C][resistance:010]:   Icon: 'mdi:flash'
[13:09:49][C][resistance:011]:   Configuration: DOWNSTREAM
[13:09:49][C][resistance:012]:   Resistor: 11200.00Ω
[13:09:49][C][resistance:013]:   Reference Voltage: 3.3V
[13:09:49][C][version.text_sensor:021]: Version Text Sensor 'nsobyvak ESPhome Version'
[13:09:49][C][version.text_sensor:021]:   Icon: 'mdi:new-box'
[13:09:49][C][nextion:117]: Nextion:
[13:09:49][C][nextion:118]:   Device Model:     NX4832F035_011C
[13:09:49][C][nextion:119]:   Firmware Version: 72
[13:09:49][C][nextion:120]:   Serial Number:    45B03401D05B9265
[13:09:49][C][nextion:121]:   Flash Size:       16777216
[13:09:49][C][nextion:122]:   Wake On Touch:    True
[13:09:49][C][ntc:014]: NTC Sensor 'nsobyvak Temperature'
[13:09:49][C][ntc:014]:   Device Class: 'temperature'
[13:09:49][C][ntc:014]:   State Class: 'measurement'
[13:09:49][C][ntc:014]:   Unit of Measurement: '°C'
[13:09:49][C][ntc:014]:   Accuracy Decimals: 1
[13:09:49][C][captive_portal:088]: Captive Portal:
[13:09:49][C][web_server:161]: Web Server:
[13:09:49][C][web_server:162]:   Address: nsobyvak.local:80
[13:09:49][C][mdns:112]: mDNS:
[13:09:49][C][mdns:113]:   Hostname: nsobyvak
[13:09:49][C][ota:093]: Over-The-Air Updates:
[13:09:49][C][ota:094]:   Address: nsobyvak.local:3232
[13:09:49][C][ota:097]:   Using Password.
[13:09:49][C][api:138]: API Server:
[13:09:49][C][api:139]:   Address: nsobyvak.local:6053
[13:09:49][C][api:143]:   Using noise encryption: NO
[13:09:49][C][wifi_info:009]: WifiInfo IPAddress 'nsobyvak IP'
[13:09:49][C][wifi_info:011]: WifiInfo SSID 'nsobyvak SSID'
[13:09:49][C][wifi_info:012]: WifiInfo BSSID 'nsobyvak BSSID'
[13:09:49][C][wifi_signal.sensor:009]: WiFi Signal 'nsobyvak RSSI'
[13:09:49][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[13:09:49][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[13:09:49][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[13:09:49][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[13:10:31][D][sensor:094]: 'nsobyvak RSSI': Sending state -60.00000 dBm with 0 decimals of accuracy
[13:10:31][D][sensor:094]: 'ntc_source': Sending state 1.55500 V with 2 decimals of accuracy
[13:10:31][D][resistance:039]: 'resistance_sensor' - Resistance 9980.5Ω
[13:10:31][D][sensor:094]: 'resistance_sensor': Sending state 9980.51562 Ω with 1 decimals of accuracy
[13:10:31][D][ntc:026]: 'nsobyvak Temperature' - Temperature: 25.0°C
[13:10:31][D][sensor:094]: 'nsobyvak Temperature': Sending state 25.04389 °C with 1 decimals of accuracy
[13:10:37][D][button:010]: 'nsobyvak Update TFT display' Pressed.
[13:10:37][D][binary_sensor:036]: 'nsobyvak Nextion display': Sending state OFF
[13:10:37][D][nextion_upload:169]: Connected
[13:10:37][D][nextion_upload:175]: Requesting URL: http://192.168.1.251:8123/local/nspanel_eu.tft
[13:10:38][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.1.251:8123/local/nspanel_eu.tft; Error: connection lost, retrying (1/5)
[13:10:38][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.1.251:8123/local/nspanel_eu.tft; Error: connection lost, retrying (2/5)
[13:10:38][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.1.251:8123/local/nspanel_eu.tft; Error: connection lost, retrying (3/5)
[13:10:38][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.1.251:8123/local/nspanel_eu.tft; Error: connection lost, retrying (4/5)
[13:10:39][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.1.251:8123/local/nspanel_eu.tft; Error: connection lost, retrying (5/5)
[13:10:39][D][nextion_upload:310]: Restarting Nextion
[13:10:41][D][nextion_upload:313]: Restarting esphome
WARNING nsobyvak.local: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for nsobyvak.local
WARNING Disconnected from API
INFO Successfully connected to nsobyvak.local
[13:10:50][D][main:915]: Nextion start - Set display brigntess
[13:10:50][D][number:054]: 'nsobyvak Display Brightness' - Setting number value
[13:10:50][D][number:113]:   New number value: 100.000000
[13:10:50][D][number:012]: 'nsobyvak Display Brightness': Sending state 100.000000
[13:10:50][D][main:916]: Nextion start - Set display dim brightness
[13:10:50][D][number:054]: 'nsobyvak Display Brightness Dimdown' - Setting number value
[13:10:50][D][number:113]:   New number value: 10.000000
[13:10:50][D][number:012]: 'nsobyvak Display Brightness Dimdown': Sending state 10.000000
[13:10:50][D][main:920]: Nextion start - Update settings page
[13:10:50][D][main:927]: Sleep mode - Turn off
[13:10:51][D][main:806]: Nextion start - Inform Home Assistant display is ready
[13:10:51][D][binary_sensor:036]: 'nsobyvak Nextion display': Sending state ON
[13:10:51][D][main:811]: Nextion start - Done!
[13:10:52][D][nspanel:949]: no page-jump
[13:11:05][D][api:102]: Accepted 192.168.1.251
[13:11:05][D][api.connection:1031]: Home Assistant 2023.8.2 (192.168.1.251): Connected successfully
[13:11:07][D][switch:016]: 'nsobyvak Relay 1 Local Fallback' Turning OFF.
[13:11:07][D][switch:016]: 'nsobyvak Relay 2 Local Fallback' Turning OFF.
[13:11:07][D][text_sensor:064]: 'nsobyvak Notification Label': Sending state ''
[13:11:07][D][text_sensor:064]: 'nsobyvak Notification Text': Sending state ''
[13:11:07][D][switch:016]: 'nsobyvak Notification unread' Turning OFF.
[13:11:09][W][nextion:396]: Nextion reported variable name invalid!
[13:11:09][W][nextion:396]: Nextion reported variable name invalid!
[13:11:09][W][nextion:396]: Nextion reported variable name invalid!
[13:11:09][W][nextion:396]: Nextion reported variable name invalid!
[13:11:09][D][text_sensor:064]: 'nsobyvak NSPanel event': Sending state '{"page": "home", "component": "currentpage", "value": "pagechange"}'
[13:11:09][D][nspanel:942]: start page-timer delay 10
[13:11:09][D][nextion_textsensor:014]: Processed text_sensor "nspanelevent" state "{"page": "home", "component": "currentpage", "value": "pagechange"}"
[13:11:09][D][text_sensor:064]: 'nsobyvak Settings Entity': Sending state '{"page": "home", "component": "currentpage", "value": "pagechange"}'
[13:11:13][D][sensor:094]: 'nsobyvak uptime': Sending state 32.30500 s with 0 decimals of accuracy
[13:11:17][D][sensor:094]: 'ntc_source': Sending state 1.54700 V with 2 decimals of accuracy
[13:11:17][D][resistance:039]: 'resistance_sensor' - Resistance 9883.9Ω
[13:11:17][D][sensor:094]: 'resistance_sensor': Sending state 9883.85742 Ω with 1 decimals of accuracy
[13:11:18][D][ntc:026]: 'nsobyvak Temperature' - Temperature: 25.3°C
[13:11:18][D][sensor:094]: 'nsobyvak Temperature': Sending state 25.26313 °C with 1 decimals of accuracy
[13:11:19][D][nspanel:949]: no page-jump
[13:11:25][D][sensor:094]: 'nsobyvak RSSI': Sending state -58.00000 dBm with 0 decimals of accuracy
[13:11:33][D][esp32.preferences:114]: Saving 2 preferences to flash...
[13:11:33][D][esp32.preferences:143]: Saving 2 preferences to flash: 2 cached, 0 written, 0 failed
[13:12:13][D][sensor:094]: 'nsobyvak uptime': Sending state 92.30600 s with 0 decimals of accuracy
[13:12:18][D][sensor:094]: 'ntc_source': Sending state 1.54900 V with 2 decimals of accuracy
[13:12:18][D][resistance:039]: 'resistance_sensor' - Resistance 9907.9Ω
[13:12:18][D][sensor:094]: 'resistance_sensor': Sending state 9907.93945 Ω with 1 decimals of accuracy
[13:12:18][D][ntc:026]: 'nsobyvak Temperature' - Temperature: 25.2°C
[13:12:18][D][sensor:094]: 'nsobyvak Temperature': Sending state 25.20828 °C with 1 decimals of accuracy
[13:12:25][D][sensor:094]: 'nsobyvak RSSI': Sending state -59.00000 dBm with 0 decimals of accuracy
```

**Comment by plhy** [comment]
Yaml log:

```
substitutions:

###### CHANGE ME START ######

  device_name: "nsobyvak" 
  wifi_ssid: "XXX"
  wifi_password: "XXX"

  nextion_update_url: "http://192.xxx.x.xxx:8123/local/nspanel_eu.tft" # URL to local tft File /config/www/nspanel_eu.tft            http://192.xxx.x.xxx:8123/local/nspanel_eu.tft
#    nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

**Comment by plhy** [comment]
> Your log says the panel is not properly connected to Home Assistant.
> 
> 1. Are you using the standard ESPHome yaml setting or have you added any customization? In this case, could you please share your ESPHome yaml settings? Please remove any sensitive information before sharing.
> 2. You can try removing your device from Home Assistant (Settings > Devices and Services > ESPHome) and then add it again.


Point 2: When I delete the ESP home integration. Won't I have to re-flash esp via wires?

**Comment by edwardtfn** [comment]
If you try with your browser ( in your computer) with this url http://192.168.1.251:8123/local/nspanel_eu.tft are you getting the file downloaded to your computer? Is the file size right compared to the one you downloaded from GitHub?

**Comment by plhy** [comment]
Not at this address: http://192.168.1.251:8123/local/nspanel_eu.tft
But when I add **s** ( https ), the same file is downloaded.

**Comment by plhy** [comment]
I changed the address in esphome yaml and the panel started. I'll see how he reacts.

**Comment by edwardtfn** [comment]
Is it displaying TFT v3.4 on the boot screen?

**Comment by plhy** [comment]
Yes, the display shows 3.4. thank you very much for your help
I have one more question. I will close the topic.

how do the chips work please and what do I do? When I set the chips to light, nothing appears. I had to put the lights in the button page. Thanks

**Comment by edwardtfn** [comment]
Chips will show up when the entity is on, otherwise they are not visible.
